# Generated by Django 6.0 on 2026-02-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_groups_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_block",
            field=models.BooleanField(default=False),
        ),
    ]
