# Generated by Django 6.0 on 2026-01-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="email",
            field=models.EmailField(max_length=150, unique=True, verbose_name="почта"),
        ),
    ]
