# Generated by Django 6.0 on 2026-01-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_alter_clients_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailattempt",
            old_name="send_at",
            new_name="attempt_time",
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="clients",
            new_name="recipients",
        ),
        migrations.AlterField(
            model_name="clients",
            name="email",
            field=models.CharField(max_length=150, unique=True, verbose_name="почта"),
        ),
    ]
