# Generated by Django 6.0 on 2026-01-30 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_rename_send_at_emailattempt_attempt_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clients",
            options={
                "permissions": [
                    ("can_all_view_clients", "Просмотр всех получателей"),
                    ("can_delete_client", "Удаление получателя"),
                    ("can_create_client", "Добавление получателя"),
                ],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_all_view_mailing", "Просмотр всех рассылок"),
                    ("can_delete_mailing", "Удаление рассылки"),
                    ("can_update_mailing", "Обновление рассылки"),
                    ("can_create_mailing", "Добавление рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_all_view_messages", "Просмотр всех сообщений"),
                    ("can_delete_message", "Удаление сообщения"),
                    ("can_update_message", "Обновление сообщения"),
                    ("can_create_message", "Добавление сообщения"),
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AddField(
            model_name="clients",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriber_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailattempt",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emailattempt_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="status_active",
            field=models.BooleanField(
                default=True, verbose_name="Возможность рассылки"
            ),
        ),
    ]
