# Generated by Django 6.0 on 2026-01-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0004_alter_clients_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата и время создания"
            ),
        ),
    ]
