# Generated by Django 6.0 on 2026-01-30 21:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0006_alter_message_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="name",
            field=models.CharField(
                default="Рассылка", max_length=100, verbose_name="Название рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mail.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата и время начала рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status_active",
            field=models.BooleanField(default=True, verbose_name="Активация рассылки"),
        ),
    ]
