# Generated by Django 6.0 on 2026-01-30 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0007_mailing_name_alter_mailing_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="recipients",
        ),
    ]
