# Generated by Django 6.0 on 2026-01-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0008_remove_mailing_recipients"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                related_name="mailings", to="mail.clients", verbose_name="Получатели"
            ),
        ),
    ]
