# Generated by Django 6.0 on 2026-01-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0009_mailing_recipients"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="recipients",
            new_name="clients",
        ),
    ]
