# Generated by Django 6.0 on 2026-02-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0010_rename_recipients_mailing_clients"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_all_view_mailing", "Просмотр всех рассылок"),
                    ("can_delete_mailing", "Удаление рассылки"),
                    ("can_update_mailing", "Обновление рассылки"),
                    ("can_create_mailing", "Добавление рассылки"),
                    ("can_deactivate_mailing", "Отключение рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
