# Generated by Django 6.0 on 2026-02-05 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0012_message_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 5, 12, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время начала рассылки",
            ),
        ),
    ]
