# Generated by Django 6.0 on 2026-02-05 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0013_alter_mailing_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 5, 22, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
    ]
