# Generated by Django 6.0 on 2026-02-06 16:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0015_alter_mailing_name_logattempt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailattempt",
            old_name="response",
            new_name="server_response",
        ),
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                related_name="clients", to="mail.clients", verbose_name="Получатели"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 6, 22, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailings",
                to="mail.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 6, 12, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время начала рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                ],
                default="Создана",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
