# Generated by Django 6.0 on 2026-02-11 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0019_alter_mailing_end_time_alter_mailing_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 11, 22, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 11, 12, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время начала рассылки",
            ),
        ),
    ]
