# Generated by Django 6.0 on 2026-02-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0020_alter_mailing_end_time_alter_mailing_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status_active",
            field=models.CharField(
                choices=[("active", "Активна"), ("inactive", "Неактивна")],
                default="active",
                max_length=20,
            ),
        ),
    ]
