# Generated by Django 6.0 on 2026-02-11 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0021_alter_mailing_status_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status_active",
            field=models.CharField(
                choices=[("active", "Активна"), ("inactive", "Неактивна")],
                default="active",
                max_length=20,
                verbose_name="Активность",
            ),
        ),
    ]
